# 导师制度 {#advisor}


## 学术导师(Adacemic Advisor)

> **你的学术导师，不是你的朋友。**

学术导师的主要职能有两条：

1. 提供必要的科研环境，包括科研软硬件条件、学习的环境、经费支持等。
2. 引导你的科研方向，并尽力指导你完成科研目标。


## 生活导师(Mentor)

> **你的生活导师并不是你的保姆**

哪些事情你应当寻求生活导师的帮助？

- 科研资源信息（在寻求帮助之前，先看一遍本实验室手册）
- 科研生活的困惑
- 职业规划
- 师生、同学关系
- 重要的且需要与有经验的研究者沟通的疑惑。


## 学生培养计划

### 研究方向

本研究组总体科研方向请参看：\@ref(sec:resinst)节。

**本组各成员的研究方向都应当是显著不同的。**

学生的研究方向主要有两个因素确定：
1. 学生个人兴趣；
2. 本组项目状况。

对于“*科研方向选择*”的几条建议：

1. 选择和放弃之前，一定要充分了解它。
2. 难易是相对的。例如：有的领域没人做，A觉得是因为难而无人做，B觉得无人做才容易出结果。有的领域已经有很成熟的分析/模拟流程，A觉得好上手容易做，B觉得已经做烂的事情，再怎么深入也只能是步人后尘，难以独树一帜。
3. 热情是好事，但必须脚踏实地一步一步走出来。
4. 空话、大话很容易说，但是科研要求你知道你所研究方向的几乎细节。你要做到每个细节都计算过、了解过、思考过。

### 时间表


| 时间点 | 学业时间 | 任务 | 任务目标 | 
|:--:|:--:|:-------------:|:-----:|
| -12个月 | 入学前一年 | 文献阅读；参与项目；补课；学软件 |  熟悉科研环境和流程 | 
| -6个月 | 入学前半年 | 文献阅读；参与项目；补课；学软件 | 掌握软件  | 
| 0-6月 | 入学 | 文献阅读；完成必修课；参与项目 | 重复了解研究方向  | 
| 7-12月 | 入学1年 | 文献阅读；完成必修课；参与项目 | 确认研究方向  | 
| 13-18月 | 入学1.5年 | 研究综述；试验设计 | 形成综述文章  | 
| 19-24月 | 入学2年 | 开展研究、试验、分析；撰写论文 | 完成试验，发表论文  | 
| 25-30月 | 入学2.5年 | 总结试验，撰写论文；开展改进试验 | 毕业论文  | 
| 31-36月 | 临近毕业 | 完成毕业论文、送审、答辩 | 学位:-)  | 


### 课程推荐

- **地理信息系统导论**
    - 掌握有关空间栅格/矢量数据的区别、格式和读写方法；
    - 熟练掌握空间数据处理、数据分析、数据投影；
    - 熟练掌握水文有关的空间数据；
    - 能够利用DEM生成流域边界和河网，了解D8等算法。
- **水文学导论**
    - 深入理解流域水循环；
    - 掌握降雨、蒸散发、入渗、产流、汇流和地下水为物理过程；
    - 了解水文统计和水文模型；
    - 掌握水文分析的基本方法和流程。
- **地下水力学**
    - 掌握基本的地下水的基本概念，如土壤孔隙度、含水量、水力学传导度、承压/非承压地下水、Duipuit Assumption；
    - 掌握地下水力学的重要公式，贝努力方程、达西定律、理查兹方程、van Genuchten方程；
    - 能够熟练建立/推导承压和非承压地下水的控制方程。
- **地学中的数值方法（有限差分、有限元）**
    - 掌握数值方法的基本原理；
    - 掌握从泰勒展开式到一阶、二阶精度有限差分方法的推导/证明过程；
    - 明确理解数值方法的稳定性、收敛性、一致性的含义和影响；
    - 掌握CFL条件的计算和证明方法；
    - 能够编程数值方法求解简单的对流扩散方程。
- **气象与气候学**
    - 了解基本的气象要素的含义和观测方法；
    - 理解水和能量在气候/气象过程中的运动规律；
    - 熟练掌握气象和气候学的基础控制方程。
- **R/Python**
    - 基本操作(安装、扩展包安装)
    - 能够使用R/Python读取各种类型数据(shapefile, GeoTiff，HDF, NetCDF等)；
    - 熟练掌握数据分析功能(基本统计、数据挖掘、空间数据处理/分析、简单爬虫)；
    - 熟练掌握做图功能（ggplot, rgl等）。



### 必读书籍

- Beven, K., 2012. Rainfall-Runoff Modelling: The Primer: Second Edition, John Wiley & Sons, Ltd, Chichester, UK. https://doi.org/10.1002/9781119951001
- Sorooshian, S., Hsu, K.-L., Coppola, E., Tomassetti, B., Verdecchia, M., Visconti, G. (Eds.), 2008. Hydrological Modelling and the Water Cycle, Water Science and Technology Library. Springer Berlin Heidelberg, Berlin, Heidelberg. https://doi.org/10.1007/978-3-540-77843-1
- 威尔·布鲁萨 著，王忠静，梁友，耿国婷 译. 2017. 水文学导论. 气象出版社. 北京
- 徐宗学, 2009. 水文模型. 科学出版社, 北京.
- 贾仰文, 王浩, 倪广恒, 2005. 分布式流域水文模型原理与实践. 中国水利水电出版社, 北京.
- Kang-tsung Chang 著，陈健飞 等 译. 2019. 地理信息系统导论. 科学出版社. 北京.
- McDonnell, J.J., 2019. Navigating an Academic Career, Special Publications. Wiley. https://doi.org/10.1002/9781119642206

