# 规则  {#rules}


## 愉快科研的一些建议

1. **有疑问请尽早问** ——
我们对任何问题都持开放态度，也不会因为你问了问题而挑剔你，但是如果有问题不问，靠个人猜测，往往会引起很多误解。 
在我们组里没有“傻问题”。


1. **对学术不端零容忍** —— 学术诚信是立身之本，如果做不到这一点，请换一个职业。

1. **保持好奇** —— 对学术中出现的每个问题都要有好奇心。虽然不一定深入研究，但是必须有所思考。

1. **尊重和褒奖他人科研成果** —— 
使用任何他人的数据、观点、方法、逻辑证明，都要给别人足够的学术肯定（Academic Credit），形式包括但不限于合理作者署名、论文致谢、广而告之等；强烈不建议使用金钱等方式答谢。肯定他人学术贡献，并不会使你的研究成果变得暗淡失色。

1. **持开放心态** —— 
对他人的观点持开放态度，学习的态度。若要否定别人的数据、逻辑或观点，要拿出比对方更坚实的证明过程。

1. **工作和生活分开** ——
为了更长久战斗在科研领域，要能够同时享受科研工作和个人生活。 

1. **尊重他人的私人空间** --
若无紧急事态，不要打扰组员的周末、假日和晚上的个人时光。 


1. **科研工作需要自由空间** ——
每个人都有不同的工作模式。工作的时间、地点、方式都存在个人倾向，选择个人最合适的方式。 但同时，在团队合作与单位管理规定之间做出适当的、合理的妥协。
 



## 学术导师的行为准则

导师与学生天生不平等，任何可能带有不平等而导致学生无法拒绝或不好意思拒绝的请求，导师都应该回避。

1. **不歧视学生** —— 
导师不因任何原因（包含但不限于性别、籍贯、疾病、相貌、专业、兴趣、家境等）而对学生有歧视语言或行动。尊重学生人格，尊重学生的个人自由。

1. **不收学生礼物** ——
学生毕业以前，不接受任何学生的礼物，包含但不限于水果、鲜花、特产、贺卡等。不接受学生或其家人请吃饭。
唯一可接受礼物为书籍，但**必须自带发票，导师按照价格报销给学生**。

1. **不要求学生做私事** ——
包含但不限于带孩子、取送快递、打扫个人办公室等。恳请学生也不要主动提出此类意愿。

1. **不干涉学生个人生活** —— 导师只负责学习和科研相关内容；学生拥有安排个人生活、保护隐私的权利。



## 给学生的建议

1. **安全是第一要务** —— 确保个人安全。事关安全的事情，尽早向导师汇报，或者寻求帮助。对导师、同事、同学的可疑或不合理行为保持警惕。

1. **进导师办公室，永远敞开门** —— 为了学生好，也为了导师好。

1. **明白学习与工作的关系** —— **学生在学习上享有充分的自主权**。无论是论文的选题，方法，还是实现目标的工具、证明逻辑、书写办法等事关学生个人科学研究的内容，导师只能指导学生，无法替代学生，更不应该替学生做决定；学生需要在其中珍惜和把握自主权。
**科研工作（即学生获得工资的缘由）由具体科研项目决定**。因此学生需要规划合理时间，按照项目设计的工具、方法和思路来完成项目所规定之任务。
工作成果可作为学生的论文成果，但也可能与学生自主选择的科研方向不同。学生在论文方向的选择上，可以选择与工作一致的方向，也可以选择不同方向，但必须预料到两种选择所导致时间和精力的冲突。




